import '../theme/globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
import localFont from 'next/font/local'

const inter = Inter({ subsets: ['latin'], display: 'swap', weight: ["300", "400", "500", "600"], variable: '--font-inter' })
const roboto = Roboto_Mono({ subsets: ['latin'], display: 'swap', weight: ["300", "400", "500", "600"], variable: '--font-roboto' })

// path start at 'app' folder
const myFont = localFont({
  src: '../../public/fonts/RobotoFlex-Regular.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App !!!!',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
